[package]
name = "bamba"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.15"
ratatui = "0.29.0"
crossterm = "0.29.0"
walkdir = "2.4.0"
anyhow = "1.0.98"