[package]
name = "owl-file-explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winsafe = { version = "0.0.19", features = ["kernel"] }
crossterm = "0.27"
ratatui = "0.25.0"
