[color_schemes]
bg = "23, 23, 23"
fg = "254, 250, 212"

[modes]
normal = "NOR"
shell = "SHL"
options = "OPS"
end = "END"

[commands]
end = "end"
exp = "exp"
ser = "ser"
scd = "scd"
del = "del"
cpy = "cpy"
opn = "opn"
mov = "mov"

[options]
ops = [
    ":end - quits from the application.",
    ":exp - explore everything inside cwd.",
    ":ser - searches for a given file inside cwd.",
    ":scd - switches the cwd to the given directory.",
    ":del - deletes a given file and moves it to recycle bin.",
    ":cpy - copies a given file.",
    ":opn - opens the contents of a given file.",
    ":mov - moves the given file to a given path."
]